sudo: required

services:
  - docker

 install: travis_wait mvn install

before_install:
  - docker build -t chaitanyakalidindi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chaitanyakalidindi/docker-react npm test
