sudo: required

services:
  - docker

 install: travis_wait mvn install

before_install:
  - docker build -t kschaitanya22/docker-react -f Dockerfile.dev .

script:
  - docker run kschaitanya22/docker-react npm run test -- --coverage
